traiterJson({
"trait":2,
"scoreJ":6,
"scoreJ5":5,
"scoreR":5,
"scoreR5":2,
"bonusJ":10,
"malusJ":24,
"bonusR":27,
"malusR":27,
"cols": [
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":5, "couleur":1},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":5, "couleur":1},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":3, "couleur":1},
	 {"nb":0, "couleur":0},
	 {"nb":5, "couleur":1},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":5, "couleur":2},
	 {"nb":5, "couleur":1},
	 {"nb":3, "couleur":2},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":4, "couleur":2},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":3, "couleur":2},
	 {"nb":0, "couleur":0},
	 {"nb":0, "couleur":0},
	 {"nb":5, "couleur":2},
	 {"nb":5, "couleur":1},
	 {"nb":0, "couleur":0},
]
});